linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - gosec
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - revive
    - unconvert
    - unused
  enable-all: false
run:
  timeout: 20m
