name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.16"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: go build -v ./...

      # Disabled for now as the tests seem to need a running XenOrchestra
      # - name: Run Unit Tests
      #   run: go test -v .
